[package]
name = "tod"
version = "0.2.7"
authors = ["Alan Vardy <alan@alanvardy.com>"]
edition = "2018"
license = "MIT"
description = "A tiny unofficial Todoist client"
readme = "README.md"
homepage = "https://github.com/alanvardy/tod"
repository = "https://github.com/alanvardy/tod"
keywords = ["cli", "todoist", "client", "tasks", "todo"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.10", features = ["json", "blocking"] }
uuid = { version = "0.4", features = ["serde", "v4"] }
dirs = "3.0"
matches = "0.1.8"
regex = "1"
chrono = "0.4.19"
chrono-tz = "0.5.3"
colored = "2.0.0"
clap = "2.33.3"

[dev-dependencies]
mockito = "0.30.0"
pretty_assertions = "0.7.2"
