[package]
name = "tod"
version = "0.1.0"
authors = ["Alan Vardy <alanvardy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.10", features = ["json", "blocking"] }
uuid = { version = "0.4", features = ["serde", "v4"] }
dirs = "3.0"
